title: JEP LLM Companion Files
description: LLM-friendly companion files for articles published in the Journal of Economic Perspectives
remote_theme: just-the-docs/just-the-docs
baseurl: "https://liegroup-dartmouth.github.io" # the subpath of your site, e.g. /blog
url: "/working-aea-jep/" # the base hostname & protocol for your site, e.g. http://example.com
aux_links_new_tab: true
nav_enabled: true
heading_anchors: true
search_enabled: true
color_scheme: light
back_to_top: true
back_to_top_text: Back to top
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
 