#!/usr/bin/env python3
"""
xhtml_to_markdown.py
====================
Convert JEP paper XHTML files to Markdown using the Claude API.

Setup
-----
    pip install anthropic
    export ANTHROPIC_API_KEY="sk-ant-..."

Configuration
-------------
Edit WORKING_PATH and PAPERS_TO_CONVERT below, then run:

    python xhtml_to_markdown.py
"""

import json
import os
import re
import sys
from pathlib import Path

import anthropic

# ── Configuration ─────────────────────────────────────────────────────────────

# Absolute path to your local copy of the repository.
WORKING_PATH = Path("/Users/jimenakiser/Desktop/xhtml_to_markdown/")

# Relative paths (from WORKING_PATH) of XHTML files to convert.
# Add or remove entries as needed.
PAPERS_TO_CONVERT = [
    # "papers/v40n1/geruso-spears/paper.xhtml",
    # "papers/v40n1/berger-herkenhoff-mongey/paper.xhtml",
    "papers/v40n1/khanna/paper.xhtml",
    # "papers/v40n1/gobbi-hannusch-rossi/paper.xhtml",
]

MODEL = "claude-sonnet-4-6"

# Maximum output tokens.  Increase if output appears truncated for longer papers.
MAX_TOKENS = 16000

# ── Transformation rules (system prompt) ──────────────────────────────────────

SYSTEM_PROMPT = """\
You are a document converter. Your task is to transform the XHTML source \
provided by the user into clean Markdown. Output exactly and only the resulting \
Markdown — no preamble, no explanation, no code fences wrapping the entire output.

The YAML frontmatter block (---…---) has already been generated by the calling \
script and prepended to the file. Do NOT output a YAML block yourself. \
Do NOT output an H1 heading for the article title. \
Begin your output directly with the italic author line described in Rule 1.

Follow these rules precisely:

1. Preamble — output these two items at the very top, in this order:
   a. Italic author line: take the text of <p class="Author">, render it as
          *Author Name(s)*
      on its own line followed by a blank line.
   b. JSON-LD code block: copy the full, verbatim contents of
      <script type="application/ld+json"> into a fenced block:
          ```json
          { … }
          ```
      followed by a blank line.

2. Document structure — CSS class → Markdown mapping:
   - Title-of-Article              →  omit entirely (title is in the YAML frontmatter)
   - Author                        →  italic line per Rule 1a
   - Drop-Cap-First-Paragraph
     and MAIN                      →  regular paragraph separated by blank lines
   - H1 (section-heading class)    →  ## Heading (H2)
   - H2 and H2-no-space-before     →  ### Heading (H3)
   - Reference-head                →  ## References
   - Reference-List
     and ereader-styles_last-ref   →  regular paragraph
   - Acknowlegement,
     Author-bio-Footnote,
     Doi_URL-Footnote              →  regular paragraph

3. Page break elements: Remove entirely all <div role="doc-pagebreak"> and
   <span role="doc-pagebreak"> elements — they carry no textual content.
   When one is embedded inside a <p> element, delete the tag only and
   join the surrounding text naturally (no extra whitespace or line break).

4. Figures and tables: Each <p class="ereader-styles_IllustrationStyle"> contains
   an anchor <a id="_idTextAnchorN"/> and an <img src="image/X.jpg"/>. Captions
   are embedded in the image files and must NOT be reproduced in the Markdown.
   Render each figure as two lines separated by a blank line:

       <a id="_idTextAnchorN"></a>

       ![](image/X.jpg)

   Discard any page-break span that appears inside the same <p> element.

5. Internal hyperlinks — universal rule: every href attribute that begins with
   "paper.xhtml#" must become a same-page link by replacing "paper.xhtml#" with
   "#". This applies to all links throughout the document without exception:

   • Figure / table links in body text:
       <a href="paper.xhtml#_idTextAnchorN"><span class="Link-Style">Figure X</span></a>
     → [Figure X](#_idTextAnchorN)

   • Footnote callout links in body text (see also Rule 6):
       href="paper.xhtml#footnote-XXX"  →  href="#footnote-XXX"

   • Footnote backlinks inside the footnote section (see also Rule 7):
       href="paper.xhtml#footnote-XXX-backlink"  →  href="#footnote-XXX-backlink"

   External links (https://, http://, mailto:) are kept unchanged and converted
   to standard Markdown: [visible text](url).

6. Footnote callouts in body text: Spans with this structure:
       <span class="_21-Footnote-callout-number-superscript _idGenCharOverride-1">
         <span><a id="footnote-XXX-backlink" role="doc-noteref"
                  href="paper.xhtml#footnote-XXX">N</a></span>
       </span>
   Convert each one to:
       <sup><a id="footnote-XXX-backlink" href="#footnote-XXX">N</a></sup>
   Preserve the id on the inner <a> tag. Apply Rule 5 to the href.

7. Footnote content — placement and formatting:
   If a <section class="_idFootnotes"> block is present (an <ol> of <li> elements),
   place it at the very end of the output under the heading:
       ## Footnotes
   Render each <li id="footnote-XXX"> as:
       <p id="footnote-XXX"><sup><a href="#footnote-XXX-backlink">N</a></sup> footnote text…</p>

   Where N is the visible footnote number (the text inside the backlink anchor
   within the <li>), not the numeric suffix of the ID.
   Note: IDs are stored in reverse order — footnote-011 holds footnote 1,
   footnote-010 holds footnote 2, and so on. Output footnotes in the order
   they appear in the <ol>, which is ascending by footnote number.
   Apply Rule 5 to all hrefs within footnote content.
   Apply Rule 9 (inline formatting) throughout footnote text.

   If no <section class="_idFootnotes"> is present in the source, omit the
   ## Footnotes heading and section entirely.

8. MathML: Convert any <math> element to a readable plain-text inline expression.
   Preserve mathematical meaning using standard notation:
   use Σ for summation, subscript/superscript notation in plain text
   (e.g., "Σ(age=15 to 49) ASFR(age, calendar year)" for a typical sum formula).
   Inline MathML stays inline; MathML in footnote display paragraphs
   (class="ereader-styles_IllustrationStyleFootnote") should also be rendered
   as a compact inline expression on the same line as surrounding text.
   Do not emit <math> tags or any MathML markup in the output.

9. Inline text formatting — apply throughout all paragraphs and footnotes:
   - <span class="_011-ITC-New-Baskerville-Std-Bold">text</span>   →  **text**
   - <span class="_01-ITC-New-Baskerville-Std-Italic">text</span>  →  *text*
   - <span class="_094-Superscriptroman …">text</span>             →  <sup>text</sup>
   - <span class="_092-Subscriptroman …">text</span>               →  <sub>text</sub>
   - <span class="_091-Subscriptitalic …">text</span>              →  <sub>text</sub>
   - <span class="_022-Unimath">text</span>                        →  text as-is (Unicode)
   - All other <span> elements (including per-character diacritic spans
     such as <span class="stix-bold-94h-x-87w">ţ</span>)          →  inner text only
   - <a href="https://…">text</a>   →  [text](https://…)
   - <a href="http://…">text</a>    →  [text](http://…)
   - <a href="mailto:…">text</a>    →  [text](mailto:…)
   Remove soft-hyphen characters (U+00AD, written &#173; in HTML) entirely.
   Replace non-breaking spaces (U+00A0, written &#160; in HTML) with regular spaces.

10. Split paragraphs: If any <p class="MAIN"> ends without a closing period
    (indicating the paragraph continues after an intervening figure), concatenate
    it with the next <p class="MAIN"> and insert the figure only after the
    completed paragraph. Page-break elements embedded mid-paragraph are not splits
    — remove them in-place per Rule 3.

11. Output section order (exactly):
    1.  Italic author line + JSON-LD code block   (Rule 1)
    2.  Main text body in original document order
        (all sections, subsections, paragraphs, and figures)
    3.  Acknowledgment paragraph  (class="Acknowlegement")
    4.  ## References heading followed by all reference-list entries
    5.  Author bio paragraph      (class="Author-bio-Footnote")
    6.  DOI / supplementary note  (class="Doi_URL-Footnote")
    7.  ## Footnotes + all footnotes  (only when footnotes exist in the source)
"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def extract_json_ld(xhtml_content: str) -> dict:
    """Parse the JSON-LD metadata block from the XHTML source."""
    match = re.search(
        r'<script\s+type=["\']application/ld\+json["\'][^>]*>(.*?)</script>',
        xhtml_content,
        re.DOTALL | re.IGNORECASE,
    )
    if not match:
        return {}
    try:
        return json.loads(match.group(1).strip())
    except json.JSONDecodeError:
        return {}


def build_yaml_frontmatter(meta: dict) -> str:
    """
    Build the Jekyll/GitHub Pages YAML frontmatter block from JSON-LD metadata.

    Output format:
        ---
        layout: default
        title: "Article Title"
        article_id: "20251234"
        sidebar: jep
        ---
    """
    title = meta.get("title", "")
    article_id = meta.get("article_id", "")
    # Escape any double-quotes inside the title for YAML safety.
    title_escaped = title.replace('"', '\\"')
    return (
        "---\n"
        "layout: default\n"
        f'title: "{title_escaped}"\n'
        f'article_id: "{article_id}"\n'
        "sidebar: jep\n"
        "---\n"
    )


def load_articles(working_path: Path) -> list[dict]:
    """
    Load article-index.json and return a flat list of article dicts.
    Returns an empty list if the file is missing or malformed.
    """
    index_path = working_path / "papers" / "article-index.json"
    if not index_path.exists():
        return []
    try:
        with open(index_path, encoding="utf-8") as fh:
            raw = json.load(fh)
    except (json.JSONDecodeError, OSError):
        return []

    if isinstance(raw, dict) and "articles" in raw:
        return raw["articles"]
    if isinstance(raw, list):
        return raw
    articles: list[dict] = []
    for value in raw.values():
        if isinstance(value, list):
            articles.extend(a for a in value if isinstance(a, dict))
    return articles


def find_article(articles: list[dict], relative_xhtml_path: str) -> dict:
    """
    Return the index entry whose paper_url ends with relative_xhtml_path.
    The paper_url in the index is a full URL such as:
        https://liegroup-dartmouth.github.io/…/papers/v40n1/geruso-spears/paper.xhtml
    We match against the relative tail.
    """
    needle = relative_xhtml_path.replace("\\", "/").lstrip("/")
    for article in articles:
        url = article.get("paper_url", "")
        if url.endswith(needle):
            return article
    return {}


def convert_paper(
    client: anthropic.Anthropic,
    xhtml_content: str,
    article_info: dict,
) -> str:
    """Send the XHTML to Claude and return the converted Markdown body string."""
    parts = ["Convert the following XHTML paper to Markdown per your instructions.\n"]

    if article_info:
        parts.append(
            "Article metadata from article-index.json (for reference):\n"
            f"```json\n{json.dumps(article_info, indent=2, ensure_ascii=False)}\n```\n"
        )

    parts.append(f"XHTML source:\n\n{xhtml_content}")

    response = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": "\n".join(parts)}],
    )

    if response.stop_reason == "max_tokens":
        print(
            "  ⚠  Output was truncated (stop_reason=max_tokens). "
            "Increase MAX_TOKENS and re-run.",
            file=sys.stderr,
        )

    return response.content[0].text


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print(
            "Error: ANTHROPIC_API_KEY environment variable is not set.\n"
            "Export it before running:\n"
            "    export ANTHROPIC_API_KEY='sk-ant-...'",
            file=sys.stderr,
        )
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)

    # Load article index (optional — used only to pass supplemental metadata).
    articles = load_articles(WORKING_PATH)
    if articles:
        print(f"Loaded article index: {len(articles)} article(s).\n")
    else:
        print("[WARN] article-index.json not found or empty — proceeding without it.\n",
              file=sys.stderr)

    success, skipped, failed = 0, 0, 0
    total = len(PAPERS_TO_CONVERT)

    for i, relative_path in enumerate(PAPERS_TO_CONVERT, start=1):
        xhtml_path = WORKING_PATH / relative_path
        output_path = xhtml_path.with_suffix(".md")

        print(f"[{i}/{total}]  {relative_path}")

        if not xhtml_path.exists():
            print("  [SKIP] File not found.\n")
            skipped += 1
            continue

        try:
            xhtml_content = xhtml_path.read_text(encoding="utf-8")
            print(f"  Source: {len(xhtml_content):,} chars")

            # Build YAML frontmatter deterministically from the JSON-LD block.
            meta = extract_json_ld(xhtml_content)
            if not meta:
                print("  [WARN] No JSON-LD block found — YAML frontmatter will be empty.")
            yaml_header = build_yaml_frontmatter(meta)

            article_info = find_article(articles, relative_path)
            if not article_info:
                print("  [WARN] No matching entry in article-index.json.")

            print(f"  Calling {MODEL} …")
            body_md = convert_paper(client, xhtml_content, article_info)

            # Concatenate: YAML (Python) + blank line + body (Claude).
            # Strip any leading newlines Claude may have emitted before the author line.
            full_markdown = yaml_header + "\n" + body_md.lstrip("\n")

            output_path.write_text(full_markdown, encoding="utf-8")
            print(
                f"  [OK]  → {output_path.relative_to(WORKING_PATH)}"
                f"  ({len(full_markdown):,} chars)\n"
            )
            success += 1

        except anthropic.APIError as exc:
            print(f"  [ERROR] API error: {exc}\n", file=sys.stderr)
            failed += 1
        except Exception as exc:
            print(f"  [ERROR] {exc}\n", file=sys.stderr)
            failed += 1

    print("─" * 50)
    print(f"Done.  ✓ {success} converted  |  ⊘ {skipped} skipped  |  ✗ {failed} failed")


if __name__ == "__main__":
    main()
